### ISSUE TITLE
No support to AMD cards, with Monero CryptoNightR!

### ISSUE THREAD

**Issue by eekthecatJP** [nanopool/nanominer#10]
Please add support to AMD card's to new CryptoNightR! and if possible dont fogert the old goods RADEON HD6000+ cards! 

Thanks very much!

**Comment by xq0404** [comment]
Example of a complete file for Monero:

[CryptoNightR]
wallet = fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
paymentId = ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
rigName = rig1
email = someemail@org
pool1 = xmr-eu1.nanopool.org:14433
pool2 = xmr-eu2.nanopool.org:14433
pool3 = xmr-us-east1.nanopool.org:14433
pool4 = xmr-us-west1.nanopool.org:14433
pool5 = xmr-asia1.nanopool.org:14433

**Comment by bycarloz** [comment]
If you add support to GPU HD 6000, I have two gpu HD5000 and HD6000 and I have good hashrate would be great that your miner has support for these graphics

**Comment by Grumpy-Dwarf** [comment]
There are two issues here actually. We are happy to release [1.3.0 version of nanominer](https://github.com/nanopool/nanominer/releases/tag/v1.3.0) with CryptoNightR implemented for AMD GPUs finally. Unfortunately only GCN GPUs are supported because we don't have enough TeraScale architecture GPUs to test and optimize performance for them. They are totally different.

All modern GPUs which are supported by AMD drivers are supported by nanominer.
