### ISSUE TITLE
Add support to cuda 8

### ISSUE THREAD

**Issue by bycarloz** [nanopool/nanominer#18]
add support to cuda 8 give life to the old graphics as several gpu fermi launches a good hashrate

**Comment by Grumpy-Dwarf** [comment]
Current minimum supported CUDA compute capability is 5.0 in nanominer. Maxwell, Pascal, Volta and Turing architectures are supported. Sorry we can't support previous generations because don't have enough of them to test and optimize and because there are too few users of such GPUs as far as we know.
You can use some other miner however which support them.
