### ISSUE TITLE
never calling reboot.bat...

### ISSUE THREAD

**Issue by joman22** [nanopool/nanominer#24]
Hello!
I'm trying to set the rig reboots immediately after hashrate has dropped below the desired level.
1. I've made the reboot.bat and it works as it should.
2. I've added the following commands:
minhashrate=555M
restarts=0

Whenever I start the miner the following message is printed:
never calling reboot.bat (always restarting the miner in case of errors)

Is this only a cosmetic error but it works as it planned or the miner has misunderstood the parameters?

Thanks!

**Comment by Grumpy-Dwarf** [comment]
There are two types of parameters for nanominer: common parameters and algorithm parameters. That's a bit confusing but this is the only way to maintain several algorithms in a single ini file we invented. Common parameters are placed before any sections while algorithm parameters are placed inside algorithm sections. That's how you can run single nanominer mining Monero and Ethereum using different worker names for example. In case algorithm parameters are placed before algorithm sections they are applied to all sections.

`restarts` is a common parameter while `minhashrate` is algorithm parameter. Looks like nanominer did not see `restarts` parameter because it was placed inside algorithm section. Here is an example config which worked for me (dual mining ETC and PASC with different hashrate threshold values and `restarts=0`):
```ini
rigname=same
restarts=0
[Ethash]
wallet=0x0000000000000000000000000000000000000000
minhashrate=100M
[RandomHash]
wallet=0
minhashrate=2K

```

**Comment by joman22** [comment]
Nicely explained. It works now. Thank you.
