### ISSUE TITLE
Feature request: Option for device enumeration based on OpenCL device order

### ISSUE THREAD

**Issue by UselessGuru** [nanopool/nanominer#30]
Currently nanominer sorts the devices by PCI busID. 
Unfortunately the PCI BusID information is not available through the OpenCL API which, as a consequence, breaks proper integration on MultiPoolMiner based software (e.g. MultipoolMiner, Nemos Miner etc.).
Could you please add an option (e.g. --deviceOrder OpenCL) which will allow nanominer to sort the devices based on OpenCL device ID?

OpenCL device order in my case is:
```
GPU#00 GeForce GTX 1080 Ti
GPU#01 GeForce GTX 1060 6GB
GPU#02 Radeon RX 580 Series (Ellesmere)
GPU#03 AMD Radeon (TM) RX 560 (Baffin)
```

Nanominer now:
```
nanominer -d
2019-06-10 07:36:23: CUDA driver version is 10.2, runtime version is 10.0
Detected 4 devices:
GPU 0  PCI 01:00.0  11264 MB  GeForce GTX 1080 Ti
GPU 1  PCI 04:00.0  6144 MB  GeForce GTX 1060 6GB
GPU 2  PCI 05:00.0  2048 MB  AMD Radeon (TM) RX 560 (Baffin)
GPU 3  PCI 09:00.0  8192 MB  Radeon RX 580 Series (Ellesmere)
```

Preferred result:

```
nanominer --deviceOrder OpenCL -d
2019-06-10 07:36:23: CUDA driver version is 10.2, runtime version is 10.0
Detected 4 devices:
GPU 0  PCI 01:00.0  11264 MB  GeForce GTX 1080 Ti
GPU 1  PCI 04:00.0  6144 MB  GeForce GTX 1060 6GB
GPU 2  PCI 09:00.0  8192 MB  Radeon RX 580 Series (Ellesmere)
GPU 3  PCI 05:00.0  2048 MB  AMD Radeon (TM) RX 560 (Baffin)
```

**Comment by Grumpy-Dwarf** [comment]
There are many orders in different programs. Our competitor miners used AMD cards then Nvidia cards order. We used to have Nvidia (enumerated by CUDA) then AMD devices. Finally what we and competitors investigated is there is no good order other than PCI address for AMD and Nvidia GPUs.
1. First of all, we use OpenCL API for AMD and CUDA for Nvidia. So need to match OpenCL order with CUDA order of Nvidia devices which is tricky since all devices are similar usually. Need to get either PCI address either GPU UUID (don't know if it is possible in OpenCL actually) on both CUDA and OpenCL to match devices.
2. There is no standard way to get PCI bus address of device in OpenCL because it is generic API for all type of GPUs, not only connected by PCI. Both AMD and Nvidia have extensions however for getting bus address through OpenCL, see https://anteru.net/blog/2014/associating-opencl-device-ids-with-gpus/
3. Platforms order is tricky. It depends on what driver was installed last and how application accesses OpenCL. Using statically linked OpenCL-icd and system-wide OpenCL.dll/OpenCL.so can give different platform orders, first depends on what is inside registry and latter depends on what OpenCL.dll/OpenCL.so you have - is it Nvidia driver version, AMD driver version, Intel's, standard ICD or whatever.
4. It was a pain for me to know but there is no such thing as devices order inside single platform. There are OpenCL platforms actually (Hello, Intel!) that can give you platform devices in any order. Different orders in same program. First I thought it is bug I need to report but then I looked through standard and did not found anything about order. We can get number of devices, we can get list of devices of given length. Order is not required to be the same on each `clGetDeviceInfo`.
So using OpenCL order after PCI order even as an option looks error-prone for me.

However I see there is a technical problem which makes proper integration impossible. Can I help implementing PCI order in MultiPoolMiner?

**Comment by UselessGuru** [comment]
@Grumpy-Dwarf 
Thank you for your information. 

> Can I help implementing PCI order in MultiPoolMiner?

Yes sure!

MultiPoolMiner relies entirely on the device order returned by OpenCL, In most cases that matches the PCI device order - but no always (kin my computer it does not)

If you know of a clever way to map the PCI id to the OpenCL id's. That's all what's needed.
Currently I have implemented an optional 'manual' mapping that re-maps the PCI id's to OpelCLID's:
```
  "DevicePciOrderMapping": {
    "GPU#00": "0",
    "GPU#01": "1",
    "GPU#02": "3",
    "GPU#03": "2"
  },
```

Or you know of a way to re-order the device order returned by OpenCL.
