### ISSUE TITLE
<error> device: 2; unspecified launch failure

### ISSUE THREAD

**Issue by ragotnicolas** [nanopool/nanominer#37]
Hello after few hours of work, the application send an error in the console log and stop to work.

2019-07-10 09:13:09: <error> System exception: 
2019-07-10 09:13:09: <error> device: 2; unspecified launch failure
2019-07-10 09:13:09: <error> Can't work on device: 2
2019-07-10 09:13:09: <info> Miner has already been restarted 3 times
2019-07-10 09:13:09: <info> Self-restarting miner process.

After the restart of the application we can see this error.

2019-07-10 09:13:18: <info> CUDA driver version is 10.2, runtime version is 10.0
2019-07-10 09:13:18: <error> CUDA call failed: unspecified launch failure
2019-07-10 09:13:18: <info> Detected 0 devices

Do you need more information to work on this issue ?

See my configuration below.
[Ethash]
wallet = 0xxxx
rigName = NANOMINER
email = xxx@gmail.com
pool1 = eth-eu1.nanopool.org:9999
pool2 = eth-eu2.nanopool.org:9999
pool3 = eth-us-east1.nanopool.org:9999
pool4 = eth-us-west1.nanopool.org:9999
pool5 = eth-asia1.nanopool.org:9999
pool6 = eth-jp1.nanopool.org:9999
pool7 = eth-au1.nanopool.org:9999
minHashrate = 125M

**Comment by Grumpy-Dwarf** [comment]
Looks like we don't restart miner in case we got `unspecified launch failure` during initialization not mining. Will try to fix eventually.
As a temporary workaround you can set up `restarts=0` option and write `reboot.bat` which reboots the rig (`shutdown /r /t 5 /f` for example). Use `reboot.sh` script if you run miner on Linux. This will reboot rig every time `unspecified launch failure` occurs while mining instead of restarting miner. This can be more robust.
This also can be a hardware issue like dying rizer or GPU 2 overclocked too much.

**Comment by ragotnicolas** [comment]
Thank you I have implemented this workaroud.
![image](https://user-images.githubusercontent.com/52598059/61176046-61833680-a5ba-11e9-8601-e09af066bf62.png)
I will provide you feedback.

**Comment by Grumpy-Dwarf** [comment]
Please put `restarts=0` before `[Ethash]` section. It's a bit confusing but this is common miner parameter not algorithm's one.

**Comment by ragotnicolas** [comment]
I don’t know why the new version of nanominer is very unstable. I have to use old driver nvidia with finminer then it’s okay.
