### ISSUE TITLE
cmdline_launcher  -device question

### ISSUE THREAD

**Issue by Minerx117** [nanopool/nanominer#41]
hi i am running nanominer with cmdline_launcher

"cmdline_launcher.bat -mport -4068 -algo cryptonightr -wallet 1QGADhdMRpp9Pk5u5zG1TrHKRrdK5R81TE.1070 -rigName x -pool1 cryptonightr.jp.nicehash.com:3375"

what would i need to add to this if i have a 4 card rig and would like to disable device 0?

eg.
have tried adding -devices 1,2,3  -devices=1,2,3

any help be very much appreciated

**Comment by Grumpy-Dwarf** [comment]
Sorry for late delay, was on vacation.
`-devices "1,2,3"` worked. Script just makes `config_cmdline.ini` config file and runs the miner. Please check it, maybe you would like it more than long single line with options. It's following for your configuration:
```ini
mport=-4068
[cryptonightr]
wallet=1QGADhdMRpp9Pk5u5zG1TrHKRrdK5R81TE.1070
rigName=x
pool1=cryptonightr.jp.nicehash.com:3375
devices=1,2,3
```
I personally don't understand while do people still use single command line arguments instead of multi-line configs 🤔
