### ISSUE TITLE
Low hash for PASC

### ISSUE THREAD

**Issue by brittonc** [nanopool/nanominer#54]
I've moved over from c3pool to pasc open pool who only use nanominer.  However, compared to rhminer which I was using on c3pool the  hash rates are massively slower.  Is something wrong with the config or is it just slower than rhminer?  I've gone from about 11-12 kH/s to 1.6 kH/s

**Comment by Grumpy-Dwarf** [comment]
We can't be slower or faster than rhminer since rhminer doesn't support RandomHash2 and we do support it. RandomHash2 algorithm hashrate is bigger than RandomHash1 however. Please check 1.7.0 release which have dropped RansomHash1 support.
Please check also which number of CPU threads are you using. Default is using all the threads which is usually the best for RandomHash2 algorithm.
