### ISSUE TITLE
Not working with NVIDIA GPU

### ISSUE THREAD

**Issue by checho221** [nanopool/nanominer#71]
Hi i was just monitoring the process and i found that it is not using my NVIDIA Graphic card:

![image](https://user-images.githubusercontent.com/10603888/74987452-304ccd80-5409-11ea-8c2b-3c248a62c80b.png)

When it starts it says that "GTX 1050 is available" 

But here i could see that it is really using the integrated intel graphic card:

![image](https://user-images.githubusercontent.com/10603888/74987634-a2bdad80-5409-11ea-930a-345201b467e0.png)

It shows a 0% usage for my NVIDIA GTX 1050 GRAPHIC CARD

how should i force it to use the NVIDIA ?

**Comment by checho221** [comment]
Of course i have the last driver installed:

![image](https://user-images.githubusercontent.com/10603888/74987916-5cb51980-540a-11ea-832d-f847dad98a89.png)

**Comment by Grumpy-Dwarf** [comment]
To see compute load of Nvidia GPU device please select "Cuda" instead of "3d" in GPU performance metrics plots. 3d engine is not loaded like it is while playing games however GPU is busy with CUDA compute tasks.
Integrated Intel GPU is not used by nanominer, it is set up to only work with Nvidia and AMD GPUs.
