### ISSUE TITLE
Dual Mining ETC and XMR

### ISSUE THREAD

**Issue by DarthMiner88** [nanopool/nanominer#74]
I did my file for dual mining ETC and XMR, and was succesful, but i thought that the miner would do the dual mining in the GPU, not with GPU for ETC and CPU for XMR, is there a way to dual mine with just the GPU?

**Comment by Grumpy-Dwarf** [comment]
The algorithms that can be done such way are dead for GPUs because all of them are compute bound and can be implemented on FPGA and cheap ASICs. That's why we call GPU+CPU mode the dual mode (two algorithms on same system), because we think previous "Ethash + other algorithm on same GPU" dual mode is dead.

XMR's RandomX algorithm is CPU-friendly, both compute and memory bound and there are no known good GPU or FPGA implementations. I don't think it is reasonable to implement it on some Ethash+RandomX GPU code.
