### ISSUE TITLE
 Low hashrate RX 570 4GB

### ISSUE THREAD

**Issue by blackcamelot** [nanopool/nanominer#89]
Hi everyone,
I've installed nanominer instead of claymore due to DAG buffer problems, but with nanominer the hashrate dropped a lot, from 29mh / s of Claymore  to 18 mh / s with Nanominer, how is it possible?
Did I forget any settings on nanominer?

Thank you

**Comment by Grumpy-Dwarf** [comment]
It's not dropping from 29 MH/s on Claymore to 18 MH/s on nanominer, it's huge boost from 0 MH/s on Claymore to 18 MH/s on nanominer. Nanominer worked fine with lower DAG sizes on 4 GB cards, hashrate is on par with Claymore.
DAG barely fits to 4 GB GPU memory now, but there are still some options to check:
- Please make sure compute mode is enabled (especially if you have 8 GB device).
- Putting GPU in PCIe slot directly instead of 1x lane riser can increase performance.
- Increasing host memory size and number of memory channels used can increase performance.
- Switching to Linux will give additional time of full-speed mining followed by smooth hashrate degradation while DAG size increases every five days.

**Comment by Novicracker** [comment]
When i build my mining machines I make sure to have the motherboard with built in Graphics. Also make sure you have set the proper memory timings for you GPU's. 
If I were you I would check out this link for info that can help you out a lot.
https://1stminingrig.com/best-bios-rom-sapphire-rx-470-8gb-mining-edition-samsung-memory-29-30-mhs/

You may not get more that what you are getting. Because of 
1. Your timings.
2. Network reliability.
3. Location.
4. Latency to the pool.
5. Letting the machine run for 1-2 hours before trying new timings.
6. System stability.
If I were you I would check to make sure that all these things are good and working.
