### ISSUE TITLE
When the Dev starts................

### ISSUE THREAD

**Issue by Novicracker** [nanopool/nanominer#90]
Ok so when the Dev starts which I always let the Dev start and run because I'm in Love with this piece of software. The only issue I'm having is that the Dev count isn't separate from the core shares count. I'm suggesting how you should separate the counts. But I would like to be able to see the shares found separate from the Dev shares to help me asses the shares to the sites shown shares. This will help me be able to put my profitability into better perspective. So please separate the Core Shares from the Dev Shares that are found.

**Comment by Novicracker** [comment]
Oh and thanks for this software. I do enjoy it.

**Comment by Grumpy-Dwarf** [comment]
Thanks, will probably make an option for this. We currently doesn't count fee shares for QuarkChain since the difficulty is very different for regular and fee mining. And dev fee shares are added together with user shares statistics on other coins. Can't just change the behavior because other mining software counts fee shares and miners usually compare number of shares per day when comparing miners.
But this is a nice feature to be added as a feature.

**Comment by Grumpy-Dwarf** [comment]
We now have `countDevShares` which can be set up to `false` in our new [nanominer v1.11 release](https://github.com/nanopool/nanominer/releases/tag/v1.11.0)
Just add:
```ini
countDevShares=false
```
to your config file to see only your shares statistics collected in miner.
