### ISSUE TITLE
low hashrate ETC nvidia p104

### ISSUE THREAD

**Issue by katka543210** [nanopool/nanominer#94]
Hello,
I have very low hashrate when mining ETC with nvidia p104 gpu, Driver Version: 450.51.06    CUDA Version: 11.0.
When mining ETC: ./nanominer config_etc.ini, output: 3.712 MH/s power 70.97W
When mining ETH: ./nanominer config.ini, output: 34.773 MH/s power 156.41W
What can cause this problem?
Thank you.

**Comment by Grumpy-Dwarf** [comment]
The problem is p104 has 4 GB of memory on board. ETC DAG doesn't fit to it. There are some tweaks to improve the hashrate:
- It can be plugged in directly to full-speed PCIe slot instead of riser.
- Switching from Windows 10 to Linux or Windows 7 saves some video memory for miner.
- Most efficient: there are 8 GB of memory on p104-100 board actually, it can be enabled using custom bios. See https://bitcointalk.org/index.php?topic=5113847.0
